/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package teamcity.slack.app

import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement
import com.fasterxml.jackson.module.kotlin.KotlinModule
import spark.Spark.*

fun main() {
    val builds = mutableListOf<Build>()

    port(getPort())
    get("/build") { _, _ ->
        builds.map { ObjectMapper().writeValueAsString(it) }
    }
    post("/build") { req, res ->
        val buildId = req.queryParams("text")
        builds.add(Build(buildId, req.queryParams("response_url")))
        res.type("application/json")
        "{\"text\": \"$buildId build request is accepted and will be processed shortly\"}"
    }
    delete("/build") { req, _ ->
        builds.removeIf {
            it.id == ObjectMapper()
                    .registerModule(KotlinModule())
                    .readValue(req.body(), BuildId::class.java).id
        }
    }
}

data class Build(val id: String, val responseUrl: String)

@JacksonXmlRootElement
data class BuildId(val id: String)

fun getPort() = ProcessBuilder().environment()["PORT"]?.toInt() ?: 4567